name: Unit testing

on:
  push:
    branches:
      - experimental
  pull_request:
    branches:
      - experimental

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Build Docker Image
      run: docker build -t image_resizer .

    - name: Run Tests
      run: docker run -v ${PWD}:/app image_resizer /bin/sh -c "cd /app/build && ./tests/image_resizer_test -s"
