name: Unit testing

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t image_resizer .

    - name: Run Tests
      run: docker run -v ${PWD}:/workspace image_resizer /bin/sh -c "cd /workspace/build && ./tests/image_resizer_test -s"
