name: Unit testing

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Build Docker Image
      run: docker build -t image_resizer .

    - name: Run Tests
      uses: addnab/docker-run-action@v3
      with:
        image: image_resizer:latest
        shell: bash
        run: |
          cd /app/build
          ./tests/image_resizer_test -s